import type { WatchlistItem } from "./types"

export const mockWatchlistItems: WatchlistItem[] = [
  {
    id: "1",
    title: "Placeholder Movie A",
    posterUrl: "/placeholder.svg?height=300&width=200",
    backdropUrl: "/placeholder.svg?height=200&width=350",
    dateAdded: "2023-12-15",
    releaseDate: "2023-01-01",
    status: "want-to-watch",
    priority: "high",
    rating: 8.0,
    genres: ["Action", "Sci-Fi"],
    runtime: 120,
    director: "Director One",
    streamingServices: ["netflix", "amazon-prime"],
  },
  {
    id: "2",
    title: "Placeholder Movie B",
    posterUrl: "/placeholder.svg?height=300&width=200",
    dateAdded: "2023-11-20",
    releaseDate: "2022-05-10",
    status: "watching",
    priority: "medium",
    progress: 50,
    rating: 7.5,
    genres: ["Drama"],
    runtime: 110,
    director: "Director Two",
    streamingServices: ["hulu"],
  },
  {
    id: "3",
    title: "Placeholder Movie C",
    posterUrl: "/placeholder.svg?height=300&width=200",
    dateAdded: "2023-10-05",
    releaseDate: "2021-08-20",
    status: "watched",
    priority: "low",
    rating: 9.0,
    genres: ["Comedy"],
    runtime: 90,
    director: "Director Three",
    streamingServices: ["disney-plus"],
  },
]
