import type { Review } from "./types"

export const mockReviews: Review[] = [
  {
    id: "review-1",
    title: "Great Movie!",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. This movie was fantastic.",
    rating: 9.0,
    date: "2024-01-15T14:30:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 10,
    unhelpfulVotes: 1,
    commentCount: 2,
    engagementScore: 80,
    author: {
      id: "user-1",
      name: "Reviewer1",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    movie: {
      id: "movie-1",
      title: "Placeholder Movie 1",
      posterUrl: "/placeholder.svg?height=150&width=100",
      year: 2023,
      genres: ["Action"],
      country: "USA",
      language: "English",
    },
  },
  {
    id: "review-2",
    title: "Interesting Plot",
    content: "The plot was very engaging. Highly recommend.",
    rating: 8.5,
    date: "2024-02-20T09:15:00Z",
    hasSpoilers: false,
    isVerified: false,
    helpfulVotes: 5,
    unhelpfulVotes: 0,
    commentCount: 1,
    engagementScore: 70,
    mediaUrls: ["/placeholder.svg?height=100&width=150"],
    author: {
      id: "user-2",
      name: "Reviewer2",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    movie: {
      id: "movie-2",
      title: "Placeholder Movie 2",
      posterUrl: "/placeholder.svg?height=150&width=100",
      year: 2024,
      genres: ["Drama"],
      country: "UK",
      language: "English",
    },
  },
]
