import type { Movie } from "./types"

export const mockMovies: Movie[] = [
  {
    id: "inception",
    title: "Inception",
    posterUrl: "/inception-movie-poster.png",
    year: "2010",
    genres: ["Science Fiction", "Action", "Thriller"],
    sidduScore: 9.2,
    popularity: 95,
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    runtime: "2h 28m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    streamingOptions: {
      US: [
        {
          id: "netflix",
          provider: "Netflix",
          logoUrl: "/netflix-inspired-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
        {
          id: "hbo",
          provider: "HBO Max",
          logoUrl: "/hbo-max-logo.png",
          type: "subscription",
          quality: "HD",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "interstellar",
    title: "Interstellar",
    posterUrl: "/interstellar-poster.png",
    year: "2014",
    genres: ["Science Fiction", "Adventure", "Drama"],
    sidduScore: 9.0,
    popularity: 92,
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    runtime: "2h 49m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    streamingOptions: {
      US: [
        {
          id: "paramount",
          provider: "Paramount+",
          logoUrl: "/generic-streaming-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "the-dark-knight",
    title: "The Dark Knight",
    posterUrl: "/dark-knight-poster.png",
    year: "2008",
    genres: ["Action", "Crime", "Drama", "Thriller"],
    sidduScore: 9.5,
    popularity: 98,
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    runtime: "2h 32m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    streamingOptions: {
      US: [
        {
          id: "hbo",
          provider: "HBO Max",
          logoUrl: "/hbo-max-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "pulp-fiction",
    title: "Pulp Fiction",
    posterUrl: "/pulp-fiction-poster.png",
    year: "1994",
    genres: ["Crime", "Drama"],
    sidduScore: 9.3,
    popularity: 90,
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    runtime: "2h 34m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    streamingOptions: {
      US: [
        {
          id: "netflix",
          provider: "Netflix",
          logoUrl: "/netflix-inspired-logo.png",
          type: "subscription",
          quality: "HD",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "parasite",
    title: "Parasite",
    posterUrl: "/parasite-movie-poster.png",
    year: "2019",
    genres: ["Comedy", "Drama", "Thriller"],
    sidduScore: 9.4,
    popularity: 93,
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    runtime: "2h 12m",
    country: "South Korea",
    language: "Korean",
    status: "streaming",
    synopsis:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    streamingOptions: {
      US: [
        {
          id: "hulu",
          provider: "Hulu",
          logoUrl: "/hulu-logo.png",
          type: "subscription",
          quality: "HD",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "the-shawshank-redemption",
    title: "The Shawshank Redemption",
    posterUrl: "/shawshank-redemption-poster.png",
    year: "1994",
    genres: ["Drama"],
    sidduScore: 9.6,
    popularity: 96,
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    runtime: "2h 22m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    streamingOptions: {
      US: [
        {
          id: "hbo",
          provider: "HBO Max",
          logoUrl: "/hbo-max-logo.png",
          type: "subscription",
          quality: "HD",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "fight-club",
    title: "Fight Club",
    posterUrl: "/fight-club-poster.png",
    year: "1999",
    genres: ["Drama"],
    sidduScore: 9.1,
    popularity: 89,
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    runtime: "2h 19m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
    streamingOptions: {
      US: [
        {
          id: "hulu",
          provider: "Hulu",
          logoUrl: "/hulu-logo.png",
          type: "subscription",
          quality: "HD",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "the-matrix",
    title: "The Matrix",
    posterUrl: "/matrix-poster.png",
    year: "1999",
    genres: ["Action", "Science Fiction"],
    sidduScore: 9.0,
    popularity: 91,
    director: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    runtime: "2h 16m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    streamingOptions: {
      US: [
        {
          id: "hbo",
          provider: "HBO Max",
          logoUrl: "/hbo-max-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "the-godfather",
    title: "The Godfather",
    posterUrl: "/classic-mob-poster.png",
    year: "1972",
    genres: ["Crime", "Drama"],
    sidduScore: 9.7,
    popularity: 94,
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
    runtime: "2h 55m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    streamingOptions: {
      US: [
        {
          id: "paramount",
          provider: "Paramount+",
          logoUrl: "/generic-streaming-logo.png",
          type: "subscription",
          quality: "HD",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "dune-part-two",
    title: "Dune: Part Two",
    posterUrl: "/dune-part-two-poster.png",
    year: "2024",
    genres: ["Science Fiction", "Adventure", "Drama"],
    sidduScore: 8.9,
    popularity: 97,
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Josh Brolin"],
    runtime: "2h 46m",
    country: "United States",
    language: "English",
    status: "theaters",
    synopsis:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    streamingOptions: {},
  },
  {
    id: "poor-things",
    title: "Poor Things",
    posterUrl: "/poor-things-poster.png",
    year: "2023",
    genres: ["Science Fiction", "Comedy", "Romance"],
    sidduScore: 8.5,
    popularity: 85,
    director: "Yorgos Lanthimos",
    cast: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe", "Ramy Youssef"],
    runtime: "2h 21m",
    country: "United Kingdom",
    language: "English",
    status: "streaming",
    synopsis:
      "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    streamingOptions: {
      US: [
        {
          id: "hulu",
          provider: "Hulu",
          logoUrl: "/hulu-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    posterUrl: "/oppenheimer-inspired-poster.png",
    year: "2023",
    genres: ["Biography", "Drama", "History"],
    sidduScore: 9.2,
    popularity: 96,
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    runtime: "3h 0m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    streamingOptions: {
      US: [
        {
          id: "peacock",
          provider: "Peacock",
          logoUrl: "/generic-streaming-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "barbie",
    title: "Barbie",
    posterUrl: "/barbie-movie-poster.png",
    year: "2023",
    genres: ["Adventure", "Comedy", "Fantasy"],
    sidduScore: 8.0,
    popularity: 98,
    director: "Greta Gerwig",
    cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera", "Kate McKinnon"],
    runtime: "1h 54m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    streamingOptions: {
      US: [
        {
          id: "max",
          provider: "Max",
          logoUrl: "/hbo-max-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "killers-of-the-flower-moon",
    title: "Killers of the Flower Moon",
    posterUrl: "/killers-of-the-flower-moon-poster.png",
    year: "2023",
    genres: ["Crime", "Drama", "History"],
    sidduScore: 8.8,
    popularity: 88,
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Robert De Niro", "Lily Gladstone", "Jesse Plemons"],
    runtime: "3h 26m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s, sparking a major F.B.I. investigation involving J. Edgar Hoover.",
    streamingOptions: {
      US: [
        {
          id: "appletv",
          provider: "Apple TV+",
          logoUrl: "/apple-tv-plus-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "the-creator",
    title: "The Creator",
    posterUrl: "/the-creator-poster.png",
    year: "2023",
    genres: ["Action", "Adventure", "Drama", "Science Fiction"],
    sidduScore: 8.2,
    popularity: 84,
    director: "Gareth Edwards",
    cast: ["John David Washington", "Gemma Chan", "Ken Watanabe", "Sturgill Simpson"],
    runtime: "2h 13m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "Against the backdrop of a war between humans and robots with artificial intelligence, a former soldier finds the secret weapon, a robot in the form of a young child.",
    streamingOptions: {
      US: [
        {
          id: "hulu",
          provider: "Hulu",
          logoUrl: "/hulu-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "challengers",
    title: "Challengers",
    posterUrl: "/challengers-poster.png",
    year: "2024",
    genres: ["Drama", "Romance", "Sport"],
    sidduScore: 8.3,
    popularity: 86,
    director: "Luca Guadagnino",
    cast: ["Zendaya", "Josh O'Connor", "Mike Faist"],
    runtime: "2h 11m",
    country: "United States",
    language: "English",
    status: "theaters",
    synopsis:
      "Follows three players who knew each other when they were teenagers as they compete in a tennis tournament to be the world-famous grand slam winner, and reignite old rivalries on and off the court.",
    streamingOptions: {},
  },
  {
    id: "asteroid-city",
    title: "Asteroid City",
    posterUrl: "/asteroid-city-poster.png",
    year: "2023",
    genres: ["Comedy", "Drama", "Romance"],
    sidduScore: 7.8,
    popularity: 79,
    director: "Wes Anderson",
    cast: ["Jason Schwartzman", "Scarlett Johansson", "Tom Hanks", "Jeffrey Wright"],
    runtime: "1h 45m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "Following a writer on his world famous fictional digest as he creates a play about a grieving father who travels with his tech-obsessed family to small rural Asteroid City to compete in a junior stargazing event, only to have his world view disrupted forever.",
    streamingOptions: {
      US: [
        {
          id: "peacock",
          provider: "Peacock",
          logoUrl: "/generic-streaming-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "top-gun-maverick",
    title: "Top Gun: Maverick",
    posterUrl: "/top-gun-maverick-inspired-poster.png",
    year: "2022",
    genres: ["Action", "Drama"],
    sidduScore: 8.7,
    popularity: 95,
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
    runtime: "2h 10m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    streamingOptions: {
      US: [
        {
          id: "paramount",
          provider: "Paramount+",
          logoUrl: "/generic-streaming-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "everything-everywhere-all-at-once",
    title: "Everything Everywhere All at Once",
    posterUrl: "/generic-sci-fi-poster.png",
    year: "2022",
    genres: ["Action", "Adventure", "Comedy", "Science Fiction"],
    sidduScore: 9.1,
    popularity: 92,
    director: "Daniel Kwan, Daniel Scheinert",
    cast: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan", "Jamie Lee Curtis"],
    runtime: "2h 19m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
    streamingOptions: {
      US: [
        {
          id: "showtime",
          provider: "Showtime",
          logoUrl: "/generic-streaming-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "the-batman",
    title: "The Batman",
    posterUrl: "/dark-knight-rises-inspired-poster.png",
    year: "2022",
    genres: ["Action", "Crime", "Drama"],
    sidduScore: 8.5,
    popularity: 90,
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Jeffrey Wright", "Colin Farrell"],
    runtime: "2h 56m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    streamingOptions: {
      US: [
        {
          id: "hbo",
          provider: "HBO Max",
          logoUrl: "/hbo-max-logo.png",
          type: "subscription",
          quality: "4K",
          url: "#",
          verified: true,
        },
      ],
    },
  },
  {
    id: "the-prestige",
    title: "The Prestige",
    posterUrl: "/prestige-poster.png",
    year: "2006",
    genres: ["Drama", "Mystery", "Science Fiction", "Thriller"],
    sidduScore: 9.0,
    popularity: 87,
    director: "Christopher Nolan",
    cast: ["Hugh Jackman", "Christian Bale", "Michael Caine", "Scarlett Johansson"],
    runtime: "2h 10m",
    country: "United States",
    language: "English",
    status: "streaming",
    synopsis:
      "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    streamingOptions: {
      US: [
        {
          id: "netflix",
          provider: "Netflix",
          logoUrl: "/netflix-inspired-logo.png",
          type: "subscription",
          quality: "HD",
          url: "#",
          verified: true,
        },
      ],
    },
  },
]

// Function to get mock movie data by ID
export function getMovieMockData(id: string) {
  return mockMovies.find((movie) => movie.id === id) || null
}
