import type { Scene } from "./types"

export const mockScenes: Scene[] = [
  {
    id: "scene-001",
    title: "Iconic Scene One",
    description: "A memorable scene from Placeholder Movie One.",
    thumbnail: "/placeholder.svg?height=150&width=250",
    duration: "1:30",
    movieId: "movie-1",
    movieTitle: "Placeholder Movie One",
    moviePoster: "/placeholder.svg?height=150&width=100",
    releaseYear: 2023,
    director: "Director Name",
    cinematographer: "Cinematographer Name",
    genres: ["action", "sci-fi"],
    sceneType: "action",
    viewCount: 100,
    commentCount: 10,
    isPopular: true,
    isVisualTreat: true,
    addedDate: "2024-01-15T14:30:00Z",
  },
  {
    id: "scene-002",
    title: "Dramatic Scene Two",
    description: "A key dramatic moment from Placeholder Movie Two.",
    thumbnail: "/placeholder.svg?height=150&width=250",
    duration: "2:15",
    movieId: "movie-2",
    movieTitle: "Placeholder Movie Two",
    moviePoster: "/placeholder.svg?height=150&width=100",
    releaseYear: 2024,
    director: "Another Director",
    cinematographer: "Another Cinematographer",
    genres: ["drama"],
    sceneType: "drama",
    viewCount: 50,
    commentCount: 5,
    isPopular: false,
    isVisualTreat: false,
    addedDate: "2024-02-10T09:15:00Z",
  },
]
