import type { IndustryProfessionalProfile } from "./types"

export const sampleIndustryProfiles: IndustryProfessionalProfile[] = [
  {
    id: "ip-001",
    userId: "user-001",
    name: "Christopher Nolan",
    officialTitle: "Film Director & Producer",
    companyAffiliation: ["Syncopy Films", "Warner Bros. Pictures"],
    bio: "Christopher Nolan is a British-American film director, producer, and screenwriter known for his distinctive directorial style characterized by nonlinear storytelling, practical visual effects, innovative soundscapes, and exploration of philosophical themes such as time, memory, and identity.\n\nAfter beginning his career with the noir thriller Following (1998), Nolan gained international recognition with Memento (2000), which was nominated for the Academy Award for Best Original Screenplay. His commercial breakthrough came with Insomnia (2002), followed by the Dark Knight Trilogy (2005-2012), which revolutionized the superhero genre. His other acclaimed works include The Prestige (2006), Inception (2010), Interstellar (2014), Dunkirk (2017), and Tenet (2020).\n\nNolan's films have grossed over $5 billion worldwide and have been nominated for 36 Academy Awards, winning 11. He is known for his commitment to filming with IMAX cameras and his advocacy for film preservation.",
    profilePhoto: "/christopher-nolan.png",
    coverPhoto: "/dark-blue-city-skyline.png",
    verificationStatus: "verified",
    verificationDocuments: [
      {
        id: "vd-001",
        type: "association",
        name: "Directors Guild of America Membership",
        url: "/placeholder.svg",
        uploadedAt: new Date("2023-01-15"),
        status: "verified",
      },
      {
        id: "vd-002",
        type: "company",
        name: "Syncopy Films Registration",
        url: "/placeholder.svg",
        uploadedAt: new Date("2023-01-15"),
        status: "verified",
      },
    ],
    verificationDate: new Date("2023-02-01"),
    isOfficial: true,
    filmography: [
      {
        id: "f-001",
        title: "Oppenheimer",
        role: "Director, Writer, Producer",
        year: 2023,
        linkedMovieId: "movie-001",
        posterUrl: "/oppenheimer-inspired-poster.png",
        description:
          "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
      },
      {
        id: "f-002",
        title: "Tenet",
        role: "Director, Writer, Producer",
        year: 2020,
        linkedMovieId: "movie-002",
        posterUrl: "/generic-spy-thriller-poster.png",
        description:
          "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
      },
      {
        id: "f-003",
        title: "Dunkirk",
        role: "Director, Writer, Producer",
        year: 2017,
        linkedMovieId: "movie-003",
        posterUrl: "/dunkirk-poster.png",
        description:
          "Allied soldiers from Belgium, the British Commonwealth and Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.",
      },
      {
        id: "f-004",
        title: "Interstellar",
        role: "Director, Writer, Producer",
        year: 2014,
        linkedMovieId: "movie-004",
        posterUrl: "/interstellar-poster.png",
        description:
          "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      },
      {
        id: "f-005",
        title: "Inception",
        role: "Director, Writer, Producer",
        year: 2010,
        linkedMovieId: "movie-005",
        posterUrl: "/inception-movie-poster.png",
        description:
          "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      },
    ],
    awards: [
      {
        id: "a-001",
        name: "Academy Award",
        category: "Best Director",
        year: 2018,
        project: "Dunkirk",
        linkedMovieId: "movie-003",
        isNomination: true,
      },
      {
        id: "a-002",
        name: "BAFTA Award",
        category: "Best Direction",
        year: 2018,
        project: "Dunkirk",
        linkedMovieId: "movie-003",
        isNomination: false,
      },
      {
        id: "a-003",
        name: "Academy Award",
        category: "Best Original Screenplay",
        year: 2011,
        project: "Inception",
        linkedMovieId: "movie-005",
        isNomination: true,
      },
      {
        id: "a-004",
        name: "Academy Award",
        category: "Best Picture",
        year: 2011,
        project: "Inception",
        linkedMovieId: "movie-005",
        isNomination: true,
      },
    ],
    pressKit: [
      {
        id: "p-001",
        type: "interview",
        title: "Christopher Nolan on the Making of Oppenheimer",
        source: "The Hollywood Reporter",
        url: "https://example.com/interview",
        date: new Date("2023-07-15"),
        thumbnail: "/christopher-nolan-interview.png",
      },
      {
        id: "p-002",
        type: "article",
        title: "How Christopher Nolan Changed Filmmaking",
        source: "Variety",
        url: "https://example.com/article",
        date: new Date("2023-05-10"),
        thumbnail: "/christopher-nolan-filmmaking.png",
      },
      {
        id: "p-003",
        type: "review",
        title: "Oppenheimer Review: Nolan's Masterpiece",
        source: "The New York Times",
        url: "https://example.com/review",
        date: new Date("2023-07-20"),
        thumbnail: "/oppenheimer-movie-review.png",
      },
    ],
    socialMedia: [
      {
        platform: "twitter",
        url: "https://twitter.com/example",
        handle: "@ChristopherNolan",
      },
      {
        platform: "instagram",
        url: "https://instagram.com/example",
        handle: "@christophernolan",
      },
    ],
    pulseChannelId: "pulse-001",
    scheduledPulses: [
      {
        id: "sp-001",
        content:
          "Thrilled to announce that we've wrapped principal photography on my latest film! Can't wait to share more details soon. The cast and crew have been absolutely phenomenal.",
        scheduledFor: new Date("2023-11-15T10:30:00"),
        status: "published",
        hashtags: ["FilmMaking", "NewProject"],
      },
      {
        id: "sp-002",
        content:
          "Thank you to everyone who came out to see Oppenheimer in IMAX. Your support for film as a medium means everything to filmmakers like myself.",
        scheduledFor: new Date("2023-12-01T14:00:00"),
        status: "scheduled",
        hashtags: ["Oppenheimer", "IMAX", "FilmIsForever"],
      },
    ],
    privacySettings: {
      profileVisibility: "public",
      contactVisibility: "industry-only",
      filmographyVisibility: "public",
      awardsVisibility: "public",
      pressKitVisibility: "public",
      socialMediaVisibility: "public",
      allowMessages: "industry-only",
      allowQuestions: true,
    },
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-11-01"),
    followerCount: 1450000,
    viewCount: 5320000,
    monthlyViews: 350000,
    lastViewedBy: [
      {
        name: "James Cameron",
        role: "Film Director",
        date: new Date("2023-11-02"),
      },
      {
        name: "Steven Spielberg",
        role: "Film Director",
        date: new Date("2023-10-28"),
      },
      {
        name: "Denis Villeneuve",
        role: "Film Director",
        date: new Date("2023-10-25"),
      },
    ],
  },
  {
    id: "ip-002",
    userId: "user-002",
    name: "Cillian Murphy",
    officialTitle: "Actor",
    companyAffiliation: [],
    bio: "Cillian Murphy is an Irish actor who has established himself as one of the most versatile performers of his generation. Known for his intense screen presence, distinctive blue eyes, and ability to portray complex characters with depth and nuance.\n\nMurphy began his career on the stage and in independent films before gaining wider recognition for his role in Danny Boyle's '28 Days Later' (2002). His collaboration with Christopher Nolan on 'Batman Begins' (2005) as the villainous Scarecrow led to further roles in Nolan's films, including 'Inception' (2010), 'Dunkirk' (2017), and his critically acclaimed lead performance in 'Oppenheimer' (2023).\n\nHe is also known for his portrayal of Tommy Shelby in the BBC crime drama series 'Peaky Blinders' (2013-2022), a role that has earned him international acclaim and a dedicated fanbase.",
    profilePhoto: "/cillian-murphy-portrait.png",
    coverPhoto: "/placeholder.svg?height=400&width=1200&query=cinematic+dramatic+background",
    verificationStatus: "verified",
    verificationDocuments: [
      {
        id: "vd-003",
        type: "association",
        name: "Screen Actors Guild Membership",
        url: "/placeholder.svg",
        uploadedAt: new Date("2023-02-10"),
        status: "verified",
      },
    ],
    verificationDate: new Date("2023-03-01"),
    isOfficial: true,
    filmography: [
      {
        id: "f-006",
        title: "Oppenheimer",
        role: "Lead Actor (J. Robert Oppenheimer)",
        year: 2023,
        linkedMovieId: "movie-001",
        posterUrl: "/oppenheimer-inspired-poster.png",
        description:
          "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
      },
      {
        id: "f-007",
        title: "A Quiet Place Part II",
        role: "Actor (Emmett)",
        year: 2021,
        linkedMovieId: "movie-006",
        posterUrl: "/placeholder.svg?height=300&width=200&query=a+quiet+place+part+2+movie+poster",
        description:
          "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize the creatures that hunt by sound are not the only threats lurking beyond the sand path.",
      },
      {
        id: "f-008",
        title: "Peaky Blinders",
        role: "Lead Actor (Thomas Shelby)",
        year: 2013,
        linkedMovieId: "tv-001",
        posterUrl: "/placeholder.svg?height=300&width=200&query=peaky+blinders+tv+poster",
        description:
          "A gangster family epic set in Birmingham, England, in 1919, centered on a gang who sew razor blades in the peaks of their caps, and their ambitious and highly dangerous boss Tommy Shelby.",
      },
      {
        id: "f-009",
        title: "Inception",
        role: "Actor (Robert Fischer)",
        year: 2010,
        linkedMovieId: "movie-005",
        posterUrl: "/inception-movie-poster.png",
        description:
          "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      },
    ],
    awards: [
      {
        id: "a-005",
        name: "Golden Globe Award",
        category: "Best Actor in a Motion Picture – Drama",
        year: 2024,
        project: "Oppenheimer",
        linkedMovieId: "movie-001",
        isNomination: true,
      },
      {
        id: "a-006",
        name: "BAFTA Award",
        category: "Best Leading Actor",
        year: 2024,
        project: "Oppenheimer",
        linkedMovieId: "movie-001",
        isNomination: true,
      },
      {
        id: "a-007",
        name: "Irish Film and Television Award",
        category: "Best Actor in a Leading Role – Film",
        year: 2023,
        project: "Oppenheimer",
        linkedMovieId: "movie-001",
        isNomination: false,
      },
    ],
    pressKit: [
      {
        id: "p-004",
        type: "interview",
        title: "Cillian Murphy on Becoming J. Robert Oppenheimer",
        source: "Vanity Fair",
        url: "https://example.com/murphy-interview",
        date: new Date("2023-07-12"),
        thumbnail: "/placeholder.svg?height=200&width=300&query=cillian+murphy+interview",
      },
      {
        id: "p-005",
        type: "article",
        title: "The Chameleonic Career of Cillian Murphy",
        source: "GQ Magazine",
        url: "https://example.com/murphy-career",
        date: new Date("2023-06-25"),
        thumbnail: "/placeholder.svg?height=200&width=300&query=cillian+murphy+photoshoot",
      },
    ],
    socialMedia: [],
    pulseChannelId: "pulse-002",
    scheduledPulses: [],
    privacySettings: {
      profileVisibility: "public",
      contactVisibility: "industry-only",
      filmographyVisibility: "public",
      awardsVisibility: "public",
      pressKitVisibility: "public",
      socialMediaVisibility: "public",
      allowMessages: "industry-only",
      allowQuestions: false,
    },
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2023-10-20"),
    followerCount: 980000,
    viewCount: 3250000,
    monthlyViews: 290000,
    lastViewedBy: [],
  },
]
